### PR TITLE
Suppress prompts in Roger

### PR DESCRIPTION
**Pull request by edwinvdgraaf**
In this pull request I layout the first code for a prompt suppressing from command line.

A few questions:

* Does this approach makes sense?
* My test started failing, something is wrong with the logger, but I dont understand why?
* How do I test uer input? Should I stub the thor function and can I expect it always to called?

### CODE REVIEW

**Comment by flurin** [comment]
I have a similar patch in the works and have the same doubts. :)

See: https://github.com/DigitPaint/roger/commit/35edd3d90c6b69db57acd10e3dabe952c0e45672

**Comment by edwinvdgraaf** [comment]
I've updated this PR so it approaches the end situation more.
Still there are a few things I don't know or like, but updated it for reconsideration anyway.

* The wrapper around Thor feels unwanted, I've created a object in which we can nest all other methods for shell prompts such as `.ask` and `.no?` This way the pollution inside `@release` is decreased. 
* @hkrutzer mentioned he prefers a `--yes-rsync`, because this allows more individual tuning of prompts. I personally don't see how we can implement this efficiently in the current situation.

**Comment by flurin** [comment]
I don't think this is the way to go. See proposal in #46

**Comment by edwinvdgraaf** [comment]
Still this refactor may have added value?

https://github.com/DigitPaint/roger/commit/840a75549dde380dee589c75f9bd32b9fadd32d3

**Pull request closed without merging**
