### PR TITLE
Feature template helpers

### PR DESCRIPTION
**Pull request by edwinvdgraaf**

### CODE REVIEW

**Comment by edwinvdgraaf** [comment]
Guessing we should add some documentation and a simple generator to smoothen making helpers?

**Comment by flurin** [comment]
Documentation: yes

Generators: What do you want to generate? A file with a module?

Also: we need tests for adding helpers from roger modules

**Comment by edwinvdgraaf** [comment]
`roger generate helper my_awesome_helper` should generate a helper in the vendor file i guess?

Also how can add helpers from a plugin?

**Comment by flurin** [comment]
Yes, modules == plugins :)  

Generators: feel free to make them

**Comment by flurin** [comment]
Documentation added. 

You can register helpers from plugins just by calling:

```
Roger::Template.register MyHelperModule
```

**Comment by hkrutzer** [comment]
:+1:

**Pull request merged**
